services:
  backend:
    build:
      context: ./Portfolio-BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
    depends_on:
      - mongo-express
  frontend:
    build:
      context: ./Portfolio-FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    hostname: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-atlas
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root

