frontend:
  url: https://portfolioedwardfe-production.up.railway.app

backend:
  url: https://portfolioedward-production.up.railway.app  # FIXED: Use deployed backend URL

website:
  domain: portfolioedwardfe-production.up.railway.app  # Use frontend domain

spring:
  data:
    mongodb:
      uri: ${DB_URL}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 465  
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com


  server:
    port: 8080

  profiles:
    active: dev

logging:
  level:
    root: INFO
    com.honouring: DEBUG
