# Common Configuration
frontend:
  url: http://localhost:3000

backend:
  url: http://localhost:8080

website:
  domain: localhost

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/portfolio
      auto-index-creation: true

  server:
    port: 8080


  profiles:
    active: dev



logging:
  level:
    root: INFO
    com.honouring: DEBUG



